### ISSUE TITLE
Mobile view switch

### ISSUE THREAD

**Issue by rmed** [guluc3m/gul-gultalks#25]
The switch from the speaker fields in mobile view is not working (and also appears duplicated)

**Comment by miguxbe** [comment]
Ok, I will try to solve this with ruby instead Foundation (JS). I think that with generating a random string and attaching this to the switch ID could solve the bug. Somewhat like this -> id: "switch-xxxx"

**Comment by miguxbe** [comment]
This bug was solved by removing the switch but in the future, we should find a workaround for this issue. The bug will remain open for now.

**Comment by adolphenom** [comment]
Could you reproduce it and post a screenshot, please?

**Comment by miguxbe** [comment]
Ok, just open to the "_ speaker_fields.html.haml" partial and check commented code at the end of the file. In order to build a proper responsive form, we have to find an alternative solution for the checkbox for touch devices. A "good" option is the switch, which comes with foundation framework, but it is not as easy to implement as the checkbox.

Try to uncomment the code and test the detailed form.

**Comment by rmed** [comment]
Fixed in commit a853018479962d9f6b7b82e66e768003c9e86cca.
